### ISSUE TITLE
Add an option to blacklist some commands

### ISSUE THREAD

**Issue by RobertAudi** [hchbaw/auto-fu.zsh#28]
Autofu fails with some commands. It's not Autofu's fault, but it would be useful to have a blacklist some commands

**Comment by hchbaw** [comment]
Hi, @AzizLight.

Yes, it can do. It uses some blacklist patterns. 
For example, if I want to ban some `svn co …` stuffs because of its slowness, it can be accomplish like this:

```
zstyle ':auto-fu:var' autoable-function/skiplbuffers 'svn co*'
```

Also, some _live_ examples really help. **Great thanks for those opening it to the public**:
https://github.com/search?q=zstyle+':auto-fu:var+autoable-function'&type=Code
(The above search query yields lots of same usage example though.)

**Comment by RobertAudi** [comment]
@hchbaw 
Ah! Thanks a lot! :+1:
